services:
  postgres_db:
    container_name: mcp_postgres_db
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    container_name: mcp_backend
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:admin@postgres_db:5432/postgres
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      OPENROUTER_BASE_URL: ${OPENROUTER_BASE_URL}
      LLM_MODEL_NAME: ${LLM_MODEL_NAME}
    depends_on:
      - postgres_db

volumes:
  postgres_data: